import { convertToModelMessages, generateId, streamText } from "ai";

import { getChatModel } from "@/lib/ai";
import { auth } from "@/lib/auth";
import {
  REFINE_MAX_PAYLOAD_BYTES,
  REFINE_SOFT_CAP_USER_TURNS,
  sanitizeRefineMessages,
} from "@/lib/refine-messages";

export const maxDuration = 60;

const REFINE_SYSTEM_PROMPT_BASE = [
  "You help a user shape a study plan before it gets converted into a day-by-day schedule.",
  "Stay narrowly scoped to plan-shaping. Goal: gather just enough to produce a good first draft.",
  "Each turn, ask 1-2 short, targeted questions. Pick the highest-leverage gap (length, prior knowledge, emphasis, format, time per day).",
  "Do NOT produce the plan, do NOT enumerate days, do NOT drift into general chat or tutoring. The structured plan is generated by a separate step the user triggers.",
  "Match the user's language. If they wrote in Spanish, respond in Spanish.",
  "Keep replies concise — a sentence or two of acknowledgement plus your questions.",
].join("\n");

const REFINE_SYSTEM_PROMPT_WRAP_UP = [
  REFINE_SYSTEM_PROMPT_BASE,
  "",
  `You have already had ${REFINE_SOFT_CAP_USER_TURNS} or more exchanges with the user. Stop asking new clarifying questions.`,
  "Briefly acknowledge what you understand and tell the user you have enough to generate the plan when they're ready.",
  "If the user keeps adding detail, integrate it but do not ask new questions.",
].join("\n");

export async function POST(req: Request) {
  const session = await auth();
  if (!session?.user) {
    return new Response("Unauthorized", { status: 401 });
  }

  const contentLength = Number(req.headers.get("content-length") ?? "0");
  if (Number.isFinite(contentLength) && contentLength > REFINE_MAX_PAYLOAD_BYTES) {
    return new Response("Payload too large", { status: 413 });
  }

  const body = (await req.json()) as { messages?: unknown };
  const messages = sanitizeRefineMessages(body.messages);
  if (!messages) {
    return new Response("Invalid messages", { status: 400 });
  }

  const userTurns = messages.filter((m) => m.role === "user").length;
  const system =
    userTurns >= REFINE_SOFT_CAP_USER_TURNS
      ? REFINE_SYSTEM_PROMPT_WRAP_UP
      : REFINE_SYSTEM_PROMPT_BASE;

  const result = streamText({
    model: getChatModel(),
    system,
    messages: await convertToModelMessages(messages),
  });

  return result.toUIMessageStreamResponse({
    originalMessages: messages,
    generateMessageId: generateId,
  });
}
